package main

import "fmt"

func main() {
	fmt.Println("######################################################################################")
	fmt.Println("Background")
	fmt.Println("Developed and backed by Google: Robert Griesemer, Rob Pike, and Ken Thompson")
	fmt.Println("Open sourced Nov 2009")
	fmt.Println("Version 1 Mar 2012")
	fmt.Println("######################################################################################")
	fmt.Println("Notable Users: Google, Docker and K8s are written in Go, AT&T, Facebook, Netflix, ...")
	fmt.Println("######################################################################################")
	fmt.Println("The free lunch is over: goroutines, channels")
	fmt.Println("The C10k problem: goroutines, production ready HTTP server")
	fmt.Println("######################################################################################")
	fmt.Println("Small language: C based syntax")
	fmt.Println("Simple language: Easy to understand and maintain")
	fmt.Println("Module system: Reusability")
	fmt.Println("Interfaces: Modularity")
	fmt.Println("######################################################################################")
	fmt.Println("Static types: yet feels dynamic")
	fmt.Println("Garbage collector: Sub millisecond pauses")
	fmt.Println("Rich and mature standard library")
	fmt.Println("Fast complilation")
	fmt.Println("Forces you to check errors")
	fmt.Println("######################################################################################")
	fmt.Println("The go tool: build, run, test, benchmark, install...")
	fmt.Println("Modules: Dependency management")
	fmt.Println("Built in profiler and tracer: with web interface")
	fmt.Println("Built in logging and metrics")
	fmt.Println("Lots of 3rd party modules")
	fmt.Println("######################################################################################")
	fmt.Println("lovable went down from 200 to 10 servers: 12% faster request times")
	fmt.Println("Stable API:")
	fmt.Println("Compliles to static executable: easy deployment")
	fmt.Println("Easy to cross compile")
	fmt.Println("######################################################################################")
	fmt.Println("People will help you")
	fmt.Println("A lot of reference material: A Tour of Go, The Go Programming Language")
	fmt.Println("GopherCon conferences")
	fmt.Println("Meetups")
	fmt.Println("######################################################################################")
	fmt.Println("The Cone of Learning: After two weeks we tend to remember 90% of what we Say and Do")
	fmt.Println("You learn something by doing it yourself, by asking questions, by thinking, and by experimenting; Richard Feynman")
	fmt.Println("######################################################################################")
}
